batch_size: 64
latent_dim: 128
learning_rate: 0.001
epochs: 50

alpha: 0.1
max_to_keep: 5

checkpoint_interval: 5
recon_log_interval: 10

checkpoint_dir: ./checkpoints
project_name: cifar10-autoencoder
