batch_size: 64
latent_dim: 128
learning_rate: 0.001
epochs: 100

alpha: 0.01 # final LR = 0.00001
max_to_keep: 5

checkpoint_interval: 5
recon_log_interval: 10

checkpoint_dir: ./checkpoints
project_name: cifar10-autoencoder
